best_accuracy: 0.6612580418586731
hp:
  Nudging_Mode: SE
  T: 8
  act_fn: gelu
  batch_size: 128
  beta: 1.0
  beta_factor: 1.0
  beta_ir: 0.0
  dataset: CIFAR100
  epochs: 25
  k: 1.0
  model: VGG5
  optim:
    w:
      lr: 0.00040802960945862367
      wd: 1.1682614965912609e-05
    x:
      lr: 0.1185464932462563
      momentum: 1.0
  se_flag: true
study: ./Exp_new/results_ResNet/VGG5_updateUPCL_CIFAR100_best
