best_accuracy: 0.6533453464508057
hp:
  Nudging_Mode: CN
  T: 8
  act_fn: gelu
  batch_size: 128
  beta: 0.25
  beta_factor: 0.0
  beta_ir: 0.0
  dataset: CIFAR100
  epochs: 25
  k: 1.0
  model: VGG5
  optim:
    w:
      lr: 8.790337082809267e-05
      wd: 0.0015896778173906186
    x:
      lr: 0.15757704248976112
      momentum: 1.0
  se_flag: true
study: ./Exp_new/results_ResNet/VGG5_updateUCNL_CIFAR100_best
