best_accuracy: 0.8953325152397156
hp:
  Nudging_Mode: CN
  T: 6
  act_fn: gelu
  batch_size: 128
  beta: 0.7
  beta_factor: 0.0
  beta_ir: 0.0
  dataset: CIFAR10
  epochs: 25
  k: 1.0
  model: VGG5
  optim:
    w:
      lr: 0.00030900360418285264
      wd: 0.0038082648172526436
    x:
      lr: 0.13148058490118797
      momentum: 0.5
  se_flag: true
study: ./Exp_new/results_ResNet/VGG5_updateUCNL_CIFAR10_best
