best_accuracy: 0.8907251358032227
hp:
  Nudging_Mode: SE
  T: 13
  act_fn: gelu
  batch_size: 128
  beta: 1.0
  beta_factor: 1.0
  beta_ir: 0.0
  dataset: CIFAR10
  epochs: 25
  k: 1.0
  model: VGG7
  optim:
    w:
      lr: 0.0003754808274066969
      wd: 8.422290346108227e-05
    x:
      lr: 0.20867926437617323
      momentum: 1.0
  se_flag: true
study: ./Exp_new/results_ResNet/VGG7_updateUPCL_CIFAR10_best
