best_accuracy: 0.6025640964508057
hp:
  Nudging_Mode: CN
  T: 9
  act_fn: gelu
  batch_size: 128
  beta: 0.1
  beta_factor: 0.0
  beta_ir: 0.0
  dataset: CIFAR100
  epochs: 25
  k: 1.0
  model: VGG9
  optim:
    w:
      lr: 2.3221836410282055e-05
      wd: 1.8381154264226124e-05
    x:
      lr: 0.5114616661932159
      momentum: 1.0
  se_flag: true
study: ./Exp_new/results_ResNet/VGG9_updateUCNL_CIFAR100_best
